baseurl      = "https://blog.vfiles.no"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
enableRobotsTXT = true
enableEmoji     = true

[author]
  name = "DiFronzo"

[params]
  mainSections = ["posts"]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A blog - Just a blog"

  contentTypeName = "posts"

  # Enable theme toggle
  #
  # This options enables the theme toggle for the theme.
  # Per default, this option is off.
  # The theme is respecting the prefers-color-scheme of the operating systeme.
  # With this option on, the page user is able to set the scheme he wants.
  enableThemeToggle = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My blog"
  keywords = "blog"
  images = [""]

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "A blog"
    subtitle = "Just a blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener">CC BY-SA 3.0</a>, except where indicated otherwise'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
